function [BW,maskedImage] = SegmentWithPolev2(RGB)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 17-Sep-2023
%----------------------------------------------------



% Threshold image with manual threshold
BW = im2gray(RGB) > 1.957600e-01;

% Open mask with disk
radius = 2;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Close mask with octagon
radius = 39;
se = strel('octagon', radius);
BW = imclose(BW, se);

% Dilate mask with octagon
radius = 3;
se = strel('octagon', radius);
BW = imdilate(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

