function [BW,maskedImage] = SegmentCrackV2(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 13-Sep-2023
%----------------------------------------------------


% Adjust data to span data range.
X=im2gray(X);

X = imadjust(X);

% Threshold image with manual threshold
BW = im2gray(X) > 1.249500e+02;

% Invert mask
BW = imcomplement(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Fill holes
BW = imfill(BW, 'holes');

% Close mask with default
radius = 7;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

