function [BW,maskedImage] = PuzzleSegmentv2(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Sep-2023
%----------------------------------------------------


% Threshold image with global threshold
BW = imbinarize(im2gray(X));

% Open mask with default
radius = 6;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Clear borders
BW = imclearborder(BW);

% Fill holes
BW = imfill(BW, 'holes');

% Fill holes
BW = imfill(BW, 'holes');

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

