function [BW,maskedImage] = segmentImagecrack154v2(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Sep-2023
%----------------------------------------------------


X  = im2gray(X);

% Threshold image with global threshold
BW = imbinarize(im2gray(X));

% Invert mask
BW = imcomplement(BW);

% Close mask with default
radius = 4;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Open mask with line
length = 14.000000;
angle = 45.000000;
se = strel('line', length, angle);
BW = imopen(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

