function [BW,maskedImage] = segmentImagecrack00146v1(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 09-Sep-2023
%----------------------------------------------------


% Threshold image with manual threshold
BW = im2gray(X) > 7.196000e+01;

% Open mask with default
radius = 4;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Close mask with default
radius = 4;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Fill holes
BW = imfill(BW, 'holes');

% Invert mask
BW = imcomplement(BW);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

